Feature/retrofit
ViktorGrigorov2910/mov_iO pull request #6
Opened 2022-07-06 11:03 UTC by ViktorGrigorov2910

Added: Glide, Retrofit and Api interface.
Implemented logic and mapping.Created Enum class for holding genre data and later converting it to string, MovieResource files for getting  the data from the API request (created separate package for resource classes). Small refactoring in xml files(movie_row.xml , fragment_movie_detail.xml)

2022-07-06 11:47 UTC, Golemanova requested changes

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/enums/Genre.kt
> +        private val VALUES = values()
do you need this?

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/models/resources/MovieDetailResource.kt
> +    val productionCompanies: List<Any>,
Why Any?

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/models/resources/MovieResource.kt
> +data class MovieResource(
Why do you have 3 objects for Movie, one is for the request with list of movies, one is for the request for movie by id, but what is the third one for?

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/repositories/MovieRepository.kt
> +        withContext(Dispatchers.IO) {
You don't need to switch the context, Retrofit does that for you

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/repositories/MovieRepository.kt
> +        id, title, imageUrl, description, releaseDate,
this is weird, either place them on one line, or one under the other :D

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/repositories/MovieRepository.kt
> +            RetrofitInstance.api.getMovieById(id , API_KEY).movieDetailMapping()
The Api key is something you need for every request, so it is better to use it directly in the api, kind of like the base url

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/repositories/MovieRepository.kt
> +private fun MovieDetailResource.movieDetailMapping(): Movie {
name of methods should have an action in them

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/repositories/MovieRepository.kt
> +    for (i in this.results) {
you can also use the map function

`this.results.map { Movie( *add values here* )}`

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/ui/moviedetail/MovieDetailFragment.kt
> +            tvAvgRating.text = movie.rating.toString().plus(" out of 10")
`"${movie.rating} out of 10" ` This is more readeble

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/ui/moviedetail/MovieDetailFragment.kt
> +                .load("https://image.tmdb.org/t/p/w500".plus(movie.imageUrl))
I believe you are going to use this url more than once, so extract it somewhere

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/ui/movielist/MovieListViewModel.kt
> +            val result = GetMoviesUseCase(MovieRepository).execute(Unit)
In the GetMovieById use case you provide the repository directly in the constructor, maybe you can do the same for this use case so your code will be consistent

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +            binding.tvGenre.text = getGenreToString(movies[position].genre!!)
It is not a good practise to use the !! too much as it can lead to crashes. Think of a way to avoid that

2022-07-06 11:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +    var genres = ""
use string builder here

2022-07-06 11:58 UTC, ViktorGrigorov2910 commented on app/src/main/java/com/io/movio/data/enums/Genre.kt
> +        private val VALUES = values()
the companion object-yes , the private val not really

2022-07-06 12:02 UTC, stantt requested changes

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/data/models/resources/MovieDetailResource.kt
> +    val belongsToCollection: Nothing? = null,
is this property really Nothing? JSON does not support Nothing as a type. Sounds like a boolean may be? If we don't need it you can just omit it from the class definition

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/data/models/Movie.kt
> +    @SerializedName("poster_path")
if Movie is the domain model, whats the need for @SerializedName ? That's an annotation marking JSON parsing when sending/receiving data to the server. Are you sending/receiving this particular class?

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/network/MovieApi.kt
> +    @GET("top_rated?")
usually the url starts with / so "/top_rated". Also no need for the ?

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/network/RetrofitInstance.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/movie/"
base url should be the actual base, not just the common sections of it. This means:

BASE_URL = "https://api.themoviedb.org/3"

and the call would be:

```
@Get("/movie/top_rated")
@Get("/movie/{movie_id}")
```

This way you actually understand the path. Way more readable than just` @Get("{movie_id}")`

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/network/MovieApi.kt
> +    @GET("top_rated?")
check next comment for the base url

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/moviedetail/MovieDetailFragment.kt
> +                .load("https://image.tmdb.org/t/p/w500".plus(movie.imageUrl))
Ideally the Fragment (aka Presentation layer) shouldn't know where the image comes from - aka "https://image.tmdb.org/t/p/w500" part. Figure out a way to bypass it and Fragment know only about `movie.imageUrl`

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +private const val BASE_IMAGE_URL = "https://image.tmdb.org/t/p/w500"
same as above comment. Other parts of the app shouldn't know where to get the image from. Figure out the way to properly map and build the url so that Presentation (Fragment, Adapter etc) only knows about a property -> imageUrl and nothing more

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
>          holder.apply {
movies[position] could just be extracted on top -> val movie = movies[position] and then just use that instead of movies[position] in all places

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +            binding.tvGenre.text = getGenreToString(movies[position].genre!!)
why `genre!!` ? If it's nullable we should assume it could be missing and react to that. If it's not nullable, no need for !!

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +private fun nameFormatter(genreCapital: String): String {
add the genres as string resources. Then introduce them as a property in the enums

enum Genre(@StringRes  val name: Int, val id: Int)

2022-07-06 12:02 UTC, stantt commented on app/src/main/java/com/io/movio/ui/movielist/adapter/MoviesAdapter.kt
> +private fun getGenreToString(genre: List<Int>): String {
too complicated. Just add the string resource representation in the enum and use it instead. Check next comment

2022-07-06 12:03 UTC, ViktorGrigorov2910 commented on app/src/main/java/com/io/movio/data/models/resources/MovieResource.kt
> +data class MovieResource(
One for the list. One for the movie that is held in the list. And one for the details because the request for movieById returns a movie with different fields (in the json )and it was crashing

2022-07-06 12:30 UTC, ViktorGrigorov2910 commented on app/src/main/java/com/io/movio/data/models/resources/MovieResource.kt
> +data class MovieResource(
Never mind , I tried using only two of the Resource classes(MovieListResource and MovieResource) and it works

2022-07-06 12:47 UTC, Golemanova commented on app/src/main/java/com/io/movio/data/models/resources/MovieResource.kt
> +data class MovieResource(
I was talking about the Movie, MovieResource and MovieDetailsResource, cause they are all in the data package. Which leads me to believe they are all data models, so maybe one of your classes isn't in the right package then?

2022-07-07 08:09 UTC, stantt commented on app/src/main/java/com/io/movio/ui/moviedetail/MovieDetailFragment.kt
> +private const val BASE_IMAGE_URL = "https://image.tmdb.org/t/p/w500"
delete me

2022-07-07 08:10 UTC, stantt approved these changes

2022-07-07 08:24 UTC, merged